# Generated by Django 5.1.7 on 2025-03-24 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video_tutorials', '0002_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codesnapshot',
            name='recording',
        ),
    ]
