# Generated by Django 5.1.7 on 2025-03-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_tutorials', '0003_remove_codesnapshot_recording'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codesnapshot',
            name='scroll_position',
            field=models.JSONField(default=dict),
        ),
    ]
