# Generated by Django 5.1.7 on 2025-03-24 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_tutorials', '0004_alter_codesnapshot_scroll_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSnapshotRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.FloatField()),
                ('code_content', models.TextField()),
                ('cursor_position', models.JSONField(default=dict)),
                ('scroll_position', models.JSONField(default=dict)),
                ('is_highlight', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='CodeSnapshot',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
        migrations.RemoveField(
            model_name='recording',
            name='user',
        ),
        migrations.AddField(
            model_name='recording',
            name='timestamp',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='codesnapshotrecording',
            name='recording',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='video_tutorials.recording'),
        ),
    ]
