# Generated by Django 5.1.7 on 2025-03-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_tutorials', '0006_remove_recording_timestamp_alter_recording_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codesnapshotrecording',
            name='recording',
        ),
        migrations.AddField(
            model_name='codesnapshotrecording',
            name='title',
            field=models.CharField(default=1, max_length=1000, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recording',
            name='title',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
