# Generated by Django 5.1.7 on 2025-03-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_tutorials', '0007_remove_codesnapshotrecording_recording_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codesnapshotrecording',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
